import Vue from 'vue'
import Vuetify, {
    VApp,
    VAppBar,
    VAvatar,
    VToolbarTitle,
    VBtn,
    VImg,
    VIcon,
    VTextField,
    VSpacer,
    VContainer,
    VContent,
    VFooter,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VList,
    VListItem,
    VListItemAvatar,
    VListItemContent,
    VListItemTitle,
    VListItemSubtitle,
    VSubheader,
    VDivider,
    VLayout,
    VRating,
    VFlex,
    VToolbar,
} from 'vuetify/lib'
import { Ripple } from 'vuetify/lib/directives'

Vue.use(Vuetify, {
    components: {
        VApp,
        VAppBar,
        VAvatar,
        VToolbarTitle,
        VBtn,
        VImg,
        VIcon,
        VTextField,
        VSpacer,
        VContainer,
        VContent,
        VFooter,
        VCard,
        VCardTitle,
        VCardText,
        VCardActions,
        VList,
        VListItem,
        VListItemAvatar,
        VListItemContent,
        VListItemTitle,
        VListItemSubtitle,
        VSubheader,
        VDivider,
        VLayout,
        VRating,
        VFlex,
        VToolbar,
    },
    directives: {
        Ripple,
    },
})

export default new Vuetify({ })